server:
  port: 3000

spring:
  application:
    name: pednav

  datasource:
    url: jdbc:mysql://pednav-db.czi2e8k28f5u.ap-northeast-2.rds.amazonaws.com:3306/audar
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: false

logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        include: health, info

jmx:
  enabled: false

aws:
  s3:
    bucket: audar-bucker1
    region: ap-northeast-2
